// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20251021192832_AddMigration_20251021_162822")]
    partial class AddMigration_20251021_162822
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Adoption", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AdoptionRequestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("AdoptionResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pendiente");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("UserId");

                    b.ToTable("Adoptions");

                    b.HasData(
                        new
                        {
                            Id = "adoption-1",
                            AdoptionRequestDate = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AnimalId = "1",
                            Description = "Interesada en adoptar a Firulais. Tengo experiencia con perros.",
                            State = "Pendiente",
                            UserId = "user-2"
                        },
                        new
                        {
                            Id = "adoption-2",
                            AdoptionRequestDate = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AdoptionResponseDate = new DateTime(2024, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AnimalId = "2",
                            Description = "Solicitud aprobada. El gato ya se encuentra en su nuevo hogar.",
                            State = "Aprobada",
                            UserId = "user-5"
                        },
                        new
                        {
                            Id = "adoption-3",
                            AdoptionRequestDate = new DateTime(2024, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AdoptionResponseDate = new DateTime(2024, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AnimalId = "3",
                            Description = "No cuenta con espacio adecuado para conejos.",
                            State = "Rechazada",
                            UserId = "user-6"
                        },
                        new
                        {
                            Id = "adoption-4",
                            AdoptionRequestDate = new DateTime(2024, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AnimalId = "6",
                            Description = "Familia con niños pequeños, buscan un conejo tranquilo.",
                            State = "Pendiente",
                            UserId = "user-7"
                        },
                        new
                        {
                            Id = "adoption-5",
                            AdoptionRequestDate = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AnimalId = "1",
                            Description = "Vivo sola y trabajo desde casa. Puedo darle mucho tiempo y atención.",
                            State = "Pendiente",
                            UserId = "user-8"
                        },
                        new
                        {
                            Id = "adoption-6",
                            AdoptionRequestDate = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AdoptionResponseDate = new DateTime(2024, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            AnimalId = "2",
                            Description = "Primera solicitud rechazada por falta de documentación.",
                            State = "Rechazada",
                            UserId = "user-2"
                        });
                });

            modelBuilder.Entity("Domain.Animal", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnimalState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AnimalState = "Disponible",
                            BirthDate = new DateTime(2018, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Como es el bichito",
                            Name = "Firulais",
                            Species = "Perro"
                        },
                        new
                        {
                            Id = "2",
                            AnimalState = "Adoptado",
                            BirthDate = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Como es el bichito",
                            Name = "Miau",
                            Species = "Gato",
                            UserId = "user-5"
                        },
                        new
                        {
                            Id = "3",
                            AnimalState = "Disponible",
                            BirthDate = new DateTime(2021, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Como es el bichito",
                            Name = "Bunny",
                            Species = "Conejo"
                        },
                        new
                        {
                            Id = "4",
                            AnimalState = "Adoptado",
                            BirthDate = new DateTime(2019, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Name = "Lola",
                            Species = "Gato",
                            UserId = "user-4"
                        },
                        new
                        {
                            Id = "5",
                            AnimalState = "Adoptado",
                            BirthDate = new DateTime(2017, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Como es el bichito",
                            Name = "Rex",
                            Species = "Perro",
                            UserId = "user-2"
                        },
                        new
                        {
                            Id = "6",
                            AnimalState = "Disponible",
                            BirthDate = new DateTime(2022, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Como es el bichito",
                            Name = "Coco",
                            Species = "Conejo"
                        },
                        new
                        {
                            Id = "7",
                            AnimalState = "Adoptado",
                            BirthDate = new DateTime(2016, 8, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Como es el bichito",
                            Name = "Pepi",
                            Species = "Pajaro",
                            UserId = "user-3"
                        });
                });

            modelBuilder.Entity("Domain.History.AnimalResponsibleHistory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResponsibleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.HasIndex("ResponsibleId");

                    b.ToTable("AnimalResponsibleHistories");

                    b.HasData(
                        new
                        {
                            Id = "arh-1",
                            AnimalId = "2",
                            AssignedDate = new DateTime(2023, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponsibleId = "user-2"
                        },
                        new
                        {
                            Id = "arh-2",
                            AnimalId = "2",
                            AssignedDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponsibleId = "user-6"
                        },
                        new
                        {
                            Id = "arh-3",
                            AnimalId = "2",
                            AssignedDate = new DateTime(2024, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponsibleId = "user-5"
                        },
                        new
                        {
                            Id = "arh-4",
                            AnimalId = "5",
                            AssignedDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponsibleId = "user-7"
                        },
                        new
                        {
                            Id = "arh-5",
                            AnimalId = "5",
                            AssignedDate = new DateTime(2024, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponsibleId = "user-2"
                        },
                        new
                        {
                            Id = "arh-6",
                            AnimalId = "4",
                            AssignedDate = new DateTime(2024, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponsibleId = "user-3"
                        },
                        new
                        {
                            Id = "arh-7",
                            AnimalId = "4",
                            AssignedDate = new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponsibleId = "user-8"
                        },
                        new
                        {
                            Id = "arh-8",
                            AnimalId = "4",
                            AssignedDate = new DateTime(2024, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponsibleId = "user-4"
                        },
                        new
                        {
                            Id = "arh-9",
                            AnimalId = "7",
                            AssignedDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponsibleId = "user-6"
                        },
                        new
                        {
                            Id = "arh-10",
                            AnimalId = "7",
                            AssignedDate = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponsibleId = "user-3"
                        },
                        new
                        {
                            Id = "arh-11",
                            AnimalId = "1",
                            AssignedDate = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponsibleId = "user-5"
                        },
                        new
                        {
                            Id = "arh-12",
                            AnimalId = "1",
                            AssignedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponsibleId = "user-8"
                        },
                        new
                        {
                            Id = "arh-13",
                            AnimalId = "3",
                            AssignedDate = new DateTime(2024, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponsibleId = "user-7"
                        });
                });

            modelBuilder.Entity("Domain.House", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AddressNumber")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Houses");

                    b.HasData(
                        new
                        {
                            Id = "house-1",
                            Address = "Zeballos",
                            AddressNumber = 1341,
                            Capacity = 2,
                            UserId = "user-4"
                        });
                });

            modelBuilder.Entity("Domain.MedicalCheckUp", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AnimalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CheckUpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("MedicalCheckUps");

                    b.HasData(
                        new
                        {
                            Id = "mc-1",
                            AnimalId = "7",
                            CheckUpDate = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Observation = "Control de rutina. Vacunas al día. Estado general excelente."
                        },
                        new
                        {
                            Id = "mc-2",
                            AnimalId = "5",
                            CheckUpDate = new DateTime(2024, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Observation = "Revisión post-adopción. El animal se ha adaptado bien. Se recomienda seguimiento en 3 meses."
                        },
                        new
                        {
                            Id = "mc-3",
                            AnimalId = "4",
                            CheckUpDate = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Observation = "Desparasitación realizada. Peso adecuado para su edad. Continuar con alimentación actual."
                        },
                        new
                        {
                            Id = "mc-4",
                            AnimalId = "1",
                            CheckUpDate = new DateTime(2024, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Observation = "Control pre-adopción. Animal en condiciones óptimas para ser adoptado."
                        },
                        new
                        {
                            Id = "mc-5",
                            AnimalId = "2",
                            CheckUpDate = new DateTime(2024, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Observation = "Revisión dental. Se detectó sarro leve. Se realizó limpieza. Buen estado general."
                        });
                });

            modelBuilder.Entity("Domain.Sighting", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SightingAddressName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SightingAddressNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SightingDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("SightingDescription")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Sightingstate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Sightings");

                    b.HasData(
                        new
                        {
                            Id = "s1",
                            SightingAddressName = "Calle Falsa",
                            SightingAddressNumber = "123",
                            SightingDateTime = new DateTime(2025, 9, 25, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            SightingDescription = "Avisté un perro corriendo solo",
                            Sightingstate = 0
                        },
                        new
                        {
                            Id = "s2",
                            SightingAddressName = "Av. Libertad",
                            SightingAddressNumber = "456",
                            SightingDateTime = new DateTime(2025, 9, 24, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            SightingDescription = "Gato atrapado en un árbol, unos pibes le estaban tirando piedras, los cagué a trompadas pero no pude bajar al gato del árbol",
                            Sightingstate = 0
                        },
                        new
                        {
                            Id = "s3",
                            SightingAddressName = "Plaza Central",
                            SightingAddressNumber = "10",
                            SightingDateTime = new DateTime(2025, 9, 23, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            SightingDescription = "Conejo perdido cerca del parque",
                            Sightingstate = 0
                        },
                        new
                        {
                            Id = "s4",
                            SightingAddressName = "Barrio Norte",
                            SightingAddressNumber = "2345",
                            SightingDateTime = new DateTime(2025, 9, 22, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            SightingDescription = "Se ve un pájaro herido",
                            Sightingstate = 0
                        },
                        new
                        {
                            Id = "s5",
                            SightingAddressName = "Ruta 5",
                            SightingAddressNumber = "2000",
                            SightingDateTime = new DateTime(2025, 9, 21, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            SightingDescription = "Avistamiento de perro callejero al borde de la ruta, pueden ser más de uno, pareciese tener crías",
                            Sightingstate = 0
                        });
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Active");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "user-1",
                            Dni = "12345678",
                            Name = "UTN",
                            Password = "123",
                            SurName = "Rosario",
                            UserName = "utn",
                            UserStatus = "Active",
                            UserType = "Admin"
                        },
                        new
                        {
                            Id = "user-2",
                            Dni = "87654321",
                            Name = "Camila",
                            Password = "123",
                            SurName = "Stella",
                            UserName = "cami",
                            UserStatus = "Active",
                            UserType = "Adoptante"
                        },
                        new
                        {
                            Id = "user-3",
                            Dni = "44180117",
                            Name = "Ignacio",
                            Password = "123",
                            SurName = "Esteves",
                            UserName = "nacho",
                            UserStatus = "Active",
                            UserType = "Voluntario"
                        },
                        new
                        {
                            Id = "user-4",
                            Dni = "11223344",
                            Name = "Nicolás",
                            Password = "123",
                            SurName = "Salerno",
                            UserName = "niko",
                            UserStatus = "Active",
                            UserType = "Transito"
                        },
                        new
                        {
                            Id = "user-5",
                            Dni = "33445566",
                            Name = "Martín",
                            Password = "123",
                            SurName = "González",
                            UserName = "martin",
                            UserStatus = "Active",
                            UserType = "Adoptante"
                        },
                        new
                        {
                            Id = "user-6",
                            Dni = "44556677",
                            Name = "Laura",
                            Password = "123",
                            SurName = "Fernández",
                            UserName = "laura",
                            UserStatus = "Active",
                            UserType = "Adoptante"
                        },
                        new
                        {
                            Id = "user-7",
                            Dni = "55667788",
                            Name = "Diego",
                            Password = "123",
                            SurName = "Rodríguez",
                            UserName = "diego",
                            UserStatus = "Active",
                            UserType = "Adoptante"
                        },
                        new
                        {
                            Id = "user-8",
                            Dni = "66778899",
                            Name = "Sofía",
                            Password = "123",
                            SurName = "López",
                            UserName = "sofia",
                            UserStatus = "Active",
                            UserType = "Adoptante"
                        });
                });

            modelBuilder.Entity("Domain.Adoption", b =>
                {
                    b.HasOne("Domain.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Animal", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.History.AnimalResponsibleHistory", b =>
                {
                    b.HasOne("Domain.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User", "Responsible")
                        .WithMany()
                        .HasForeignKey("ResponsibleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");

                    b.Navigation("Responsible");
                });

            modelBuilder.Entity("Domain.House", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.MedicalCheckUp", b =>
                {
                    b.HasOne("Domain.Animal", "Animal")
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Animal");
                });
#pragma warning restore 612, 618
        }
    }
}
